Revise README. (read extended commit message)
carykh/jumpcutter pull request #25
Opened 2019-04-11 10:40 UTC by RONTheCookie

* add Arch Linux instructions
* add instructions for other OS'
* move NixOS instructions

P.S: I made the AUR package (:

2019-04-11 11:36 UTC, balsoft commented
Could you rename NixOS section back to Nix?

2019-04-11 11:36 UTC, balsoft requested changes
Could you rename NixOS section back to Nix?

2019-04-11 11:36 UTC, balsoft commented on README.md
> +### NixOS
Please rename back to nix. NixOS is a linux distro, Nix is a package manager. Nix can be used on other distros as well.

2019-04-11 11:40 UTC, nevercast commented
Can you link to the AUR repo too

2019-04-11 19:14 UTC, CoolOppo commented on README.md
> +### NixOS
Or how about "Nix Package Manager" as that disambiguates whether you mean the package manager or simply "all *nix distros".

2019-04-11 21:06 UTC, RONTheCookie commented on README.md
> +### NixOS
Done (:

2023-10-03 17:10 UTC, closed without merging

2023-10-03 17:10 UTC, ckiee commented
Cleaning my site-wide GitHub PR list.